import React, { useEffect } from 'react';
import { KPICard } from '../components/KPICard';
import { TrendChart } from '../components/TrendChart';
import { useWeeklySeries } from '../hooks/useWeeklySeries';

const fmt = {
  usd:  v => v == null ? '—' : `$${Number(v).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`,
  pct:  v => v == null ? '—' : `${v}%`,
  num:  v => v == null ? '—' : Number(v).toLocaleString(),
  days: v => v == null ? '—' : `${v}d`,
};

const DEFS = {
  totalBrands:   'Count of manufacturer brands with at least one active, purchasable SKU on Birch. More vetted brands means more catalog depth.',
  totalSKUs:     'Count of individual product listings currently active and purchasable. Should grow in proportion to brand count.',
  newBrands:     'Number of new manufacturer brands that went live on the platform in the last 7 days. Measures supply-side pipeline velocity.',
  concentration: 'Percentage of total GMV generated by the top 5 brands this week. Above 60% indicates supply-side risk.',
  fulfillment:   'Mean time (in days) between order placement and manufacturer shipping confirmation this week. Proxy for SLA compliance.',
  overallReturn: 'Percentage of all delivered orders resulting in a return or refund this week. Brand-level breakdown available on double-click.',
};

const CAT_COLORS = {
  'Clothes':'#C8763A','Toys':'#5A7A5C','Feeding':'#378ADD',
  'Bath & Body':'#7A5C8A','Nursery':'#3A8A8A',
  'Pacifiers & Teethers':'#854F0B','Diapering':'#5F8AC8',
  'Transport':'#8A7A3A','Maternity':'#8A4A5A','Other':'#C8BFB0',
};

function PageShell({ title, onBack, children }) {
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, margin: '16px 0 18px' }}>
        <button onClick={onBack} style={{ background: '#F0EDE6', border: '0.5px solid #E0DDD6', borderRadius: 7, padding: '4px 10px', fontSize: 11, color: '#3D3226', cursor: 'pointer', fontFamily: 'DM Sans, sans-serif' }}>
          ← Dashboard
        </button>
        <div style={{ fontSize: 15, fontWeight: 700, color: '#3D3226', letterSpacing: '0.02em' }}>{title}</div>
      </div>
      {children}
    </div>
  );
}

function SectionLabel({ children }) {
  return (
    <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.08em', color: '#8C8A85', textTransform: 'uppercase', margin: '20px 0 8px' }}>
      {children}
    </div>
  );
}

function ChartCard({ title, children, id }) {
  return (
    <div id={id} style={{ background: '#FFFFFF', border: '0.5px solid #E0DDD6', borderRadius: 10, padding: '12px 14px' }}>
      <div style={{ fontSize: 12, fontWeight: 600, color: '#3D3226', marginBottom: 10 }}>{title}</div>
      {children}
    </div>
  );
}

function CatalogByCategoryCard({ data: catData }) {
  if (!catData?.length) return null;
  const total = catData.reduce((s, r) => s + r.skus, 0);
  const maxSkus = Math.max(...catData.map(d => d.skus), 1);
  return (
    <div style={{ background: '#FFFFFF', border: '0.5px solid #E0DDD6', borderRadius: 10, padding: '12px 14px', height: '100%' }}>
      <div style={{ fontSize: 12, fontWeight: 600, color: '#3D3226', marginBottom: 10 }}>Catalog by category</div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 40px 40px 68px', gap: '0 6px', fontSize: 10 }}>
        {['Category', 'Brands', 'SKUs', 'Share'].map((h, i) => (
          <div key={h} style={{ fontWeight: 700, color: '#8C8A85', textTransform: 'uppercase', letterSpacing: '0.06em', paddingBottom: 6, borderBottom: '1px solid #E0DDD6', textAlign: i === 0 ? 'left' : 'right' }}>{h}</div>
        ))}
        {catData.map((row, i) => {
          const color = CAT_COLORS[row.category] || '#C8BFB0';
          const pct = total > 0 ? Math.round((row.skus / total) * 100) : 0;
          const barW = Math.round((row.skus / maxSkus) * 100);
          return (
            <React.Fragment key={i}>
              <div style={{ padding: '4px 0', borderBottom: '0.5px solid #F0EDE6', display: 'flex', alignItems: 'center', gap: 5 }}>
                <span style={{ width: 7, height: 7, borderRadius: '50%', background: color, display: 'inline-block', flexShrink: 0 }} />
                <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{row.category}</span>
              </div>
              <div style={{ padding: '4px 0', borderBottom: '0.5px solid #F0EDE6', textAlign: 'right', fontFamily: 'DM Mono, monospace' }}>{row.brands}</div>
              <div style={{ padding: '4px 0', borderBottom: '0.5px solid #F0EDE6', textAlign: 'right', fontFamily: 'DM Mono, monospace' }}>{row.skus}</div>
              <div style={{ padding: '4px 0', borderBottom: '0.5px solid #F0EDE6', display: 'flex', alignItems: 'center', gap: 4 }}>
                <div style={{ flex: 1, height: 5, background: '#F0EDE6', borderRadius: 99, overflow: 'hidden' }}>
                  <div style={{ height: '100%', width: `${barW}%`, background: color, opacity: 0.7, borderRadius: 99 }} />
                </div>
                <span style={{ fontSize: 9, color: '#8C8A85', width: 26, textAlign: 'right', fontVariantNumeric: 'tabular-nums' }}>{pct}%</span>
              </div>
            </React.Fragment>
          );
        })}
      </div>
    </div>
  );
}

export function MarketplacePage({ data, onBack, scrollTarget }) {
  const { weeklyData, loading: trendLoading } = useWeeklySeries('shopify');

  useEffect(() => {
    if (!scrollTarget) return;
    const timer = setTimeout(() => {
      document.getElementById(scrollTarget)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 80);
    return () => clearTimeout(timer);
  }, [scrollTarget]);

  const m = data?.marketplace;

  return (
    <PageShell title="Marketplace & Supply" onBack={onBack}>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, alignItems: 'start' }}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
          <KPICard label="Total brands live"          value={fmt.num(m?.totalBrands)}         change={null} changeLabel={`+${m?.newBrandsThisWeek ?? 0} this week`} definition={DEFS.totalBrands} />
          <KPICard label="Total SKUs live"            value={fmt.num(m?.totalSKUs)}           change={null} definition={DEFS.totalSKUs} />
          <KPICard label="New brands (week)"          value={fmt.num(m?.newBrandsThisWeek)}   change={null} definition={DEFS.newBrands} />
          <KPICard
            label="Top 5 brand concentration"
            value={fmt.pct(m?.brandConcentration)}
            change={null}
            definition={DEFS.concentration}
            drillTitle="Brand GMV breakdown"
            drillData={(m?.gmvByBrand || []).slice(0, 8).map(b => ({ label: b.brand, value: b.gmv, formatted: fmt.usd(b.gmv) }))}
          />
          <KPICard label="Avg fulfillment time"  value={fmt.days(m?.avgFulfillmentDays)} change={null} definition={DEFS.fulfillment} />
          <KPICard label="Overall return rate"   value={fmt.pct(m?.overallReturnRate)}   change={null} definition={DEFS.overallReturn} />
        </div>
        <CatalogByCategoryCard data={m?.catalogByCategory} />
      </div>

      <SectionLabel>Weekly Trends</SectionLabel>

      {trendLoading && (
        <div style={{ fontSize: 12, color: '#8C8A85', marginBottom: 8 }}>Loading weekly trend data…</div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
        <ChartCard title="Avg Fulfillment Days" id="trend-avg-fulfill">
          <TrendChart
            id="trend-avg-fulfill-chart"
            data={weeklyData.map(w => ({ weekStart: w.weekStart, value: w.avgFulfillmentDays }))}
            label="Avg Fulfillment Days"
            color="#5A7A5C"
            valueFormatter={v => v != null ? v + 'd' : '—'}
          />
        </ChartCard>

        <ChartCard title="Overall Return Rate" id="trend-overall-return">
          <TrendChart
            id="trend-overall-return-chart"
            data={weeklyData.map(w => ({ weekStart: w.weekStart, value: w.returnRate }))}
            label="Overall Return Rate"
            color="#A32D2D"
            valueFormatter={v => v != null ? v + '%' : '—'}
          />
        </ChartCard>
      </div>

      <div style={{ height: 40 }} />
    </PageShell>
  );
}
