/**
 * App.jsx — Birch Metrics Dashboard
 * Features: brand colors, today strip, slide-out sidebar,
 * bold headers, metric definitions, ET timezone.
 */

import React, { useState, useRef } from 'react';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { useDashboardData } from './hooks/useDashboardData';
import { KPICard } from './components/KPICard';
import { AIChat } from './components/AIChat';
import { TodayStrip } from './components/TodayStrip';
import { Sidebar } from './components/Sidebar';
import { ChatTranscriptModal, customerAdminUrl } from './components/ChatTranscriptModal';
import { QueryExport } from './components/QueryExport';

const fmt = {
  usd:    v => v == null ? '—' : `$${Number(v).toLocaleString('en-US', { minimumFractionDigits:0, maximumFractionDigits:0 })}`,
  usdDec: v => v == null ? '—' : `$${Number(v).toFixed(2)}`,
  pct:    v => v == null ? '—' : `${v}%`,
  num:    v => v == null ? '—' : Number(v).toLocaleString(),
  days:   v => v == null ? '—' : `${v}d`,
};

const DEFS = {
  gmv:           'Total value of all orders placed in the period, before deductions. Tracked as rolling last 7 complete days (midnight ET to midnight ET). The primary top-line growth metric.',
  orders:        'Count of completed orders in the last 7 complete days. Tracked alongside GMV to understand whether revenue growth is driven by more orders or higher order values.',
  aov:           'GMV divided by number of orders for the week. Measures how much customers spend per transaction.',
  itemsPerOrder: 'Average number of SKUs included in each order this week. A rising number signals catalog depth and cross-sell effectiveness.',
  cancellation:  'Percentage of orders cancelled after placement, before fulfilment, this week. High rates may signal pricing, shipping, or trust issues.',
  returnRate:    'Percentage of delivered orders resulting in a return or refund this week. A key quality and trust signal for a curated marketplace.',
  cartAbandon:   'Percentage of sessions where a customer added to cart but did not complete checkout. Sourced from GA4. Industry average is 65–75%.',
  mau:           'Monthly Active Users — unique buyers with at least one order in the last 30 complete days (midnight ET). The north star growth metric.',
  wau:           'Weekly Active Users — unique buyers with at least one order in the last 7 complete days. Provides a faster weekly pulse.',
  newCustomers:  'Net new customers who made their first-ever purchase in the last 7 complete days. Leading indicator for MAU growth 4–6 weeks out.',
  newOrdersPct:  'Percentage of orders this week from first-time customers. High share signals strong acquisition.',
  returningPct:  'Percentage of orders this week from customers who have purchased before. Rising share signals growing loyalty.',
  conversion:    'Percentage of unique site visitors who completed a purchase. Sourced from GA4. Rolling 7-day window. Target: 5%. Year-one benchmark: 1.5–3%.',
  totalBrands:   'Count of manufacturer brands with at least one active, purchasable SKU on Birch. More vetted brands means more catalog depth.',
  totalSKUs:     'Count of individual product listings currently active and purchasable. Should grow in proportion to brand count.',
  newBrands:     'Number of new manufacturer brands that went live on the platform in the last 7 days. Measures supply-side pipeline velocity.',
  concentration: 'Percentage of total GMV generated by the top 5 brands this week. Above 60% indicates supply-side risk.',
  fulfillment:   'Mean time (in days) between order placement and manufacturer shipping confirmation this week. Proxy for SLA compliance.',
  overallReturn: 'Percentage of all delivered orders resulting in a return or refund this week. Brand-level breakdown available on double-click.',
  listSize:      'Total number of profiles across all Klaviyo email and SMS lists. A direct CAC reduction lever as the list grows.',
  // GA4 Website
  totalSessions:      'Total website sessions on birchstore.com in the last 7 complete days. A session starts when a user lands on the site and ends after 30 minutes of inactivity. Primary top-of-funnel volume metric.',
  bounceRate:         'Percentage of sessions where the visitor left without any interaction. Lower is better. Industry average for e-commerce is 40–55%.',
  avgSessionDuration: 'Average time visitors spend on the site per session. Longer durations signal content resonance and purchase intent.',
  pagesPerSession:    'Average number of pages viewed per session. Higher numbers indicate deeper browsing and product discovery.',
  newUserPct:         'Percentage of sessions from first-time visitors this week. High share signals strong top-of-funnel reach from marketing.',
};

function SectionLabel({ id, children }) {
  return (
    <div id={id} style={{
      fontSize:13, fontWeight:700, letterSpacing:'0.1em',
      color:'#3D3226', textTransform:'uppercase',
      margin:'24px 0 10px', paddingBottom:7,
      borderBottom:'2px solid #C8BFB0',
      scrollMarginTop: 16,
    }}>
      {children}
    </div>
  );
}

const STOP_WORDS = new Set([
  'a','an','the','is','are','was','were','be','been','being','have','has','had',
  'do','does','did','will','would','could','should','may','might','can','cant',
  'i','my','me','we','our','you','your','it','its','this','that','these','those',
  'and','or','but','in','on','at','to','for','of','with','from','by','about',
  'what','how','why','when','where','which','who','get','show','tell','give','see',
  'please','birch','want','need','looking','find','know','like','just','also',
  'more','some','any','all','not','no','so','if','up','out','than','then','them',
]);

function WordCloud({ queries }) {
  if (!queries?.length) {
    return (
      <div style={{ display:'flex', alignItems:'center', justifyContent:'center', height:100, color:'#8C8A85', fontSize:12 }}>
        ⏳ Data builds as customers use Ask Birch
      </div>
    );
  }

  const wordCount = {};
  queries.forEach(({ query, count }) => {
    query.toLowerCase().replace(/[^a-z\s]/g, ' ').split(/\s+/).forEach(word => {
      if (word.length > 2 && !STOP_WORDS.has(word)) {
        wordCount[word] = (wordCount[word] || 0) + count;
      }
    });
  });

  const words = Object.entries(wordCount)
    .map(([word, count]) => ({ word, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 50);

  if (!words.length) return null;

  const maxCount = words[0].count;
  const COLORS = ['#3D3226','#5A7A5C','#378ADD','#C8763A','#7A5C8A','#3A8A8A','#854F0B','#5F5E5A'];

  return (
    <div style={{ display:'flex', flexWrap:'wrap', gap:'6px 14px', alignItems:'center', justifyContent:'center', padding:'14px 8px', minHeight:110 }}>
      {words.map(({ word, count }, i) => {
        const ratio = count / maxCount;
        const size = Math.round(10 + ratio * 20);
        const weight = ratio > 0.6 ? 700 : ratio > 0.3 ? 600 : 400;
        const color = COLORS[i % COLORS.length];
        const opacity = 0.55 + ratio * 0.45;
        return (
          <span key={word} title={`${count} mention${count !== 1 ? 's' : ''}`}
            style={{ fontSize:size, fontWeight:weight, color, opacity, cursor:'default', lineHeight:1.3, transition:'opacity 0.15s' }}
            onMouseEnter={e => e.target.style.opacity = 1}
            onMouseLeave={e => e.target.style.opacity = opacity}>
            {word}
          </span>
        );
      })}
    </div>
  );
}

function ChartCard({ title, children, style }) {
  return (
    <div style={{ background:'#FFFFFF', border:'0.5px solid #E0DDD6', borderRadius:10, padding:'12px 14px', ...style }}>
      <div style={{ fontSize:12, fontWeight:600, color:'#3D3226', marginBottom:10 }}>{title}</div>
      {children}
    </div>
  );
}

const CustomTooltip = ({ active, payload, label, prefix='' }) => {
  if (!active || !payload?.length) return null;
  return (
    <div style={{ background:'#FFFFFF', border:'0.5px solid #E0DDD6', borderRadius:6, padding:'6px 10px', fontSize:12 }}>
      <div style={{ color:'#8C8A85', marginBottom:2 }}>{label}</div>
      {payload.map((p,i) => <div key={i} style={{ color:p.color, fontWeight:500 }}>{prefix}{typeof p.value==='number' ? p.value.toLocaleString() : p.value}</div>)}
    </div>
  );
};

export default function App() {
  const { data, loading, error, lastUpdated, refresh } = useDashboardData();
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [activeSection, setActiveSection] = useState('orders');
  const [chatSessionId, setChatSessionId] = useState(null);
  const metricsRef = useRef(null);

  const now = new Date();
  const weekLabel = `Week of ${now.toLocaleDateString('en-US', { month:'short', day:'numeric', year:'numeric' })}`;

  const handleSidebarClose = (sectionId) => {
    setSidebarOpen(false);
    if (sectionId) {
      setActiveSection(sectionId);
      setTimeout(() => {
        const el = document.getElementById(`sec-${sectionId}`);
        if (el) el.scrollIntoView({ behavior:'smooth', block:'start' });
      }, 60);
    }
  };

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=DM+Mono:wght@400&display=swap');
        * { box-sizing:border-box; margin:0; padding:0; }
        body { font-family:'DM Sans',sans-serif; background:#F7F5EF; color:#1A1A1A; -webkit-font-smoothing:antialiased; }
        @keyframes slideIn { from{opacity:0;transform:translateY(-6px)} to{opacity:1;transform:translateY(0)} }
        @keyframes fadeUp  { from{opacity:0;transform:translateY(12px)} to{opacity:1;transform:translateY(0)} }
        .kpi-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:8px; }
        .chart-row { display:grid; grid-template-columns:1fr 1fr; gap:12px; margin-top:8px; }
        .metrics-pane { padding:0 20px 20px; overflow-y:auto; animation:fadeUp 0.3s ease; }
        @media (max-width:767px) {
          .kpi-grid { grid-template-columns: repeat(2,1fr) !important; }
          .chart-row { grid-template-columns: 1fr !important; }
          .desktop-only { display:none !important; }
          .topbar-right-full { display:none !important; }
          .topbar-right-mobile { display:flex !important; }
        }
        @media (min-width:768px) {
          .topbar-right-mobile { display:none !important; }
          .main-grid { grid-template-columns: 1fr 320px !important; }
        }
        ::-webkit-scrollbar { width:4px; }
        ::-webkit-scrollbar-thumb { background:#E0DDD6; border-radius:99px; }
      `}</style>

      <Sidebar open={sidebarOpen} onClose={handleSidebarClose} activeSection={activeSection} />

      <div style={{ display:'flex', flexDirection:'column', height:'100vh', overflow:'hidden' }}>

        {/* Topbar */}
        <div style={{ background:'#EDE8DE', borderBottom:'1px solid #C8BFB0', padding:'0 20px', display:'flex', alignItems:'center', justifyContent:'space-between', height:44, flexShrink:0 }}>
          <div style={{ display:'flex', alignItems:'center', gap:10 }}>
            <button
              onClick={() => setSidebarOpen(true)}
              aria-label="Open navigation"
              style={{ width:32, height:32, borderRadius:7, background:'#3D3226', border:'none', cursor:'pointer', display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center', gap:4, padding:8, flexShrink:0 }}
            >
              {[0,1,2].map(i => <div key={i} style={{ width:14, height:1.5, background:'#F5F2EA', borderRadius:99 }} />)}
            </button>
            <span style={{ fontSize:15, fontWeight:500, color:'#3D3226', letterSpacing:'0.5px' }}><strong>Birch</strong> Metrics</span>
            <span style={{ fontSize:10, background:'#C8D5C0', color:'#3D4E3E', padding:'2px 8px', borderRadius:99, fontWeight:500 }}>Internal</span>
          </div>
          <div className="topbar-right-full" style={{ display:'flex', alignItems:'center', gap:16, fontSize:12, color:'#7A6E62' }}>
            {lastUpdated && <span>Updated {lastUpdated.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span>}
            <span style={{ display:'flex', alignItems:'center', gap:5 }}>
              <span style={{ width:6, height:6, borderRadius:'50%', background:'#7A9E7E', display:'inline-block' }} />
              Live · Shopify + Klaviyo{data?.website?.connected ? ' + GA4' : ''}
            </span>
            <span style={{ color:'#A89C8E' }}>{weekLabel}</span>
            <button onClick={refresh} style={{ background:'#3D3226', border:'none', borderRadius:6, color:'#F5F2EA', fontSize:11, padding:'4px 10px', cursor:'pointer' }}>↻ Refresh</button>
          </div>
          <div className="topbar-right-mobile" style={{ alignItems:'center', gap:8 }}>
            <span style={{ display:'flex', alignItems:'center', gap:4, fontSize:11, color:'#7A6E62' }}>
              <span style={{ width:6, height:6, borderRadius:'50%', background:'#7A9E7E', display:'inline-block' }} />
              Live
            </span>
            <button onClick={refresh} style={{ background:'#3D3226', border:'none', borderRadius:6, color:'#F5F2EA', fontSize:11, padding:'4px 8px', cursor:'pointer' }}>↻</button>
          </div>
        </div>

        {/* Today strip */}
        <TodayStrip today={data?.today} />

        {/* Main layout */}
        <div className='main-grid' style={{ display:'grid', gridTemplateColumns:'1fr', flex:1, overflow:'hidden' }}>

          {/* Metrics pane */}
          <div className="metrics-pane" ref={metricsRef} style={{ borderRight:'0.5px solid #E0DDD6' }}>

            {loading && !data && (
              <div style={{ display:'flex', alignItems:'center', justifyContent:'center', height:200, color:'#8C8A85', fontSize:13 }}>
                Loading live data from Shopify…
              </div>
            )}

            {error && (
              <div style={{ margin:'20px 0', padding:'12px 14px', background:'#FCEBEB', border:'0.5px solid #E24B4A', borderRadius:8, fontSize:13, color:'#A32D2D' }}>
                ⚠ {error} — check API credentials in environment variables
              </div>
            )}

            {data && (
              <>
                {/* #1 Orders */}
                <SectionLabel id="sec-orders">Orders & Transactions</SectionLabel>
                <div className="kpi-grid">
                  <KPICard label="GMV (week)"       value={fmt.usd(data.orders.gmv)}           change={data.orders.gmvWoW}     definition={DEFS.gmv}
                    drillTitle="GMV by brand" drillData={(data.orders.gmvByBrand||[]).slice(0,8).map(b=>({label:b.brand,value:b.gmv,formatted:fmt.usd(b.gmv)}))} />
                  <KPICard label="Orders placed"    value={fmt.num(data.orders.orderCount)}      change={data.orders.ordersWoW}  definition={DEFS.orders}
                    drillTitle="Orders by category" drillData={(data.orders.gmvByCategory||[]).slice(0,8).map(c=>({label:c.category,value:c.gmv,formatted:fmt.usd(c.gmv)}))} />
                  <KPICard label="Avg order value"  value={fmt.usdDec(data.orders.aov)}          change={data.orders.aovWoW}     definition={DEFS.aov} />
                  <KPICard label="Items per order"  value={data.orders.itemsPerOrder}             change={null}                   definition={DEFS.itemsPerOrder} />
                  <KPICard label="Cancellation rate" value={fmt.pct(data.orders.cancellationRate)} change={null}                  definition={DEFS.cancellation} />
                  <KPICard label="Return rate"      value={fmt.pct(data.orders.returnRate)}       change={null}                   definition={DEFS.returnRate} />
                </div>

                <ChartCard title="Daily GMV — last 14 days" style={{ marginTop:10 }}>
                  <ResponsiveContainer width="100%" height={160}>
                    <LineChart data={data.orders.dailyGMV} margin={{top:4,right:8,bottom:0,left:0}}>
                      <XAxis dataKey="date" tick={{fontSize:10,fill:'#8C8A85'}} axisLine={false} tickLine={false} />
                      <YAxis tick={{fontSize:10,fill:'#8C8A85'}} axisLine={false} tickLine={false} tickFormatter={v=>`$${(v/1000).toFixed(1)}k`} width={42} />
                      <Tooltip content={<CustomTooltip prefix="$" />} />
                      <Line type="monotone" dataKey="gmv" stroke="#5A7A5C" strokeWidth={2} dot={{r:2,fill:'#5A7A5C'}} activeDot={{r:4}} />
                    </LineChart>
                  </ResponsiveContainer>
                </ChartCard>

                {/* #2 Customers */}
                <SectionLabel id="sec-customers">Customers</SectionLabel>
                <div className="kpi-grid">
                  <KPICard label="MAU"               value={fmt.num(data.customers.mau)}              change={null}                        changeLabel="30 complete days" definition={DEFS.mau} />
                  <KPICard label="WAU"               value={fmt.num(data.customers.wau)}              change={null}                        definition={DEFS.wau} />
                  <KPICard label="New customers"     value={fmt.num(data.customers.newCustomerCount)} change={data.customers.newCustomersWoW} definition={DEFS.newCustomers} />
                  <KPICard label="New orders %"      value={fmt.pct(data.customers.newOrdersPct)}     change={null}                        definition={DEFS.newOrdersPct} />
                  <KPICard label="Returning orders %" value={fmt.pct(data.customers.returningOrdersPct)} change={null}                     definition={DEFS.returningPct} />
                  <KPICard label="Conversion rate"   value={data.customers.conversionRate ? fmt.pct(data.customers.conversionRate) : null} change={null} changeLabel="GA4 pending" definition={DEFS.conversion} />
                </div>

                <ChartCard title="What are customers asking? — last 7 days" style={{ marginTop:10 }}>
                  <WordCloud queries={data.askBirch?.topQueries} />
                </ChartCard>

                {/* #3 Operations */}
                <SectionLabel id="sec-operations">Operations</SectionLabel>
                <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10, marginTop:4 }}>

                  {/* Dwelling orders table */}
                  <div style={{ background:'#FFFFFF', border:'0.5px solid #E0DDD6', borderRadius:10, padding:'12px 14px', overflow:'hidden' }}>
                    <div style={{ display:'flex', alignItems:'center', gap:6, marginBottom:10 }}>
                      <span style={{ fontSize:12, fontWeight:600, color:'#3D3226' }}>Dwelling orders</span>
                      <span style={{ fontSize:10, background:'#F0EDE6', color:'#5F5E5A', padding:'1px 7px', borderRadius:99, fontWeight:600 }}>
                        {(data.operations?.dwelling?.length || 0)} items
                      </span>
                    </div>
                    {(data.operations?.dwelling?.length || 0) === 0 ? (
                      <div style={{ fontSize:12, color:'#8C8A85', padding:'8px 0' }}>No orders dwelling &gt;24h ✓</div>
                    ) : (
                      <div style={{ overflowX:'auto' }}>
                        <div style={{ display:'grid', gridTemplateColumns:'72px 1fr 64px 56px', gap:'0 6px', fontSize:10, minWidth:280 }}>
                          {['Order #','Item','Brand','Dwell'].map(h => (
                            <div key={h} style={{ fontWeight:700, color:'#8C8A85', textTransform:'uppercase', letterSpacing:'0.06em', paddingBottom:5, borderBottom:'1px solid #E0DDD6', whiteSpace:'nowrap' }}>{h}</div>
                          ))}
                          {(data.operations?.dwelling || []).map((item, i) => {
                            const dwellColor = item.dwellHours > 48 ? '#A32D2D' : item.dwellHours > 36 ? '#854F0B' : '#8C8A85';
                            return (
                              <React.Fragment key={i}>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6' }}>
                                  <a href={`https://admin.shopify.com/store/birchstoreco/orders/${item.orderId}`} target="_blank" rel="noopener noreferrer"
                                    style={{ fontFamily:'DM Mono, monospace', fontSize:10, color:'#378ADD', textDecoration:'none' }}>
                                    {item.orderName}
                                  </a>
                                </div>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6', color:'#3D3226', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }} title={item.title}>{item.title}</div>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6' }}>
                                  {item.isFBB
                                    ? <span style={{ color:'#6B3FA0', fontWeight:600 }}>FBB</span>
                                    : <span style={{ color:'#5F5E5A' }}>{item.brand}</span>}
                                </div>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6', color:dwellColor, fontWeight:500, fontFamily:'DM Mono, monospace' }}>{item.dwellHours}h</div>
                              </React.Fragment>
                            );
                          })}
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Late deliveries table */}
                  <div style={{ background:'#FFFFFF', border:'0.5px solid #E0DDD6', borderRadius:10, padding:'12px 14px', overflow:'hidden' }}>
                    <div style={{ display:'flex', alignItems:'center', gap:6, marginBottom:10 }}>
                      <span style={{ fontSize:12, fontWeight:600, color:'#3D3226' }}>Late deliveries</span>
                      <span style={{ fontSize:10, background:'#F0EDE6', color:'#5F5E5A', padding:'1px 7px', borderRadius:99, fontWeight:600 }}>
                        {(data.operations?.late?.length || 0)} items
                      </span>
                    </div>
                    {(data.operations?.late?.length || 0) === 0 ? (
                      <div style={{ fontSize:12, color:'#8C8A85', padding:'8px 0' }}>No late deliveries ✓</div>
                    ) : (
                      <div style={{ overflowX:'auto' }}>
                        <div style={{ display:'grid', gridTemplateColumns:'72px 1fr 64px 80px 36px', gap:'0 6px', fontSize:10, minWidth:340 }}>
                          {['Order #','Item','Brand','Carrier / Dest','Days'].map(h => (
                            <div key={h} style={{ fontWeight:700, color:'#8C8A85', textTransform:'uppercase', letterSpacing:'0.06em', paddingBottom:5, borderBottom:'1px solid #E0DDD6', whiteSpace:'nowrap' }}>{h}</div>
                          ))}
                          {(data.operations?.late || []).map((item, i) => {
                            const daysColor = item.daysOld > 7 ? '#A32D2D' : '#854F0B';
                            return (
                              <React.Fragment key={i}>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6' }}>
                                  <a href={`https://admin.shopify.com/store/birchstoreco/orders/${item.orderId}`} target="_blank" rel="noopener noreferrer"
                                    style={{ fontFamily:'DM Mono, monospace', fontSize:10, color:'#378ADD', textDecoration:'none' }}>
                                    {item.orderName}
                                  </a>
                                </div>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6', color:'#3D3226', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }} title={item.title}>{item.title}</div>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6' }}>
                                  {item.isFBB
                                    ? <span style={{ color:'#6B3FA0', fontWeight:600 }}>FBB</span>
                                    : <span style={{ color:'#5F5E5A' }}>{item.brand}</span>}
                                </div>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6', color:'#5F5E5A', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{item.carrier} / {item.destination}</div>
                                <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6', color:daysColor, fontWeight:600, fontFamily:'DM Mono, monospace' }}>{item.daysOld}d</div>
                              </React.Fragment>
                            );
                          })}
                        </div>
                      </div>
                    )}
                  </div>

                </div>

                {/* #4 Website Traffic — GA4 */}
                <SectionLabel id="sec-website">Website Traffic</SectionLabel>

                {data.website?.connected === false && (
                  <div style={{ padding:'12px 14px', background:'#FAEEDA', border:'0.5px solid #E8C97A', borderRadius:8, fontSize:12, color:'#854F0B', marginBottom:10 }}>
                    ⏳ GA4 service account pending access — data will populate automatically once Jagrati adds the service account as Viewer on the property.
                  </div>
                )}

                <div className="kpi-grid">
                  <KPICard
                    label="Sessions (week)"
                    value={data.website.totalSessions != null ? fmt.num(data.website.totalSessions) : null}
                    change={data.website.totalSessionsWoW}
                    changeLabel={data.website.totalSessions == null ? 'GA4 pending' : null}
                    definition={DEFS.totalSessions}
                  />
                  <KPICard
                    label="Bounce rate"
                    value={data.website.bounceRate != null ? fmt.pct(data.website.bounceRate) : null}
                    change={null}
                    changeLabel={data.website.bounceRate == null ? 'GA4 pending' : 'lower is better'}
                    definition={DEFS.bounceRate}
                  />
                  <KPICard
                    label="Avg session duration"
                    value={data.website.avgSessionDuration}
                    change={null}
                    changeLabel={data.website.avgSessionDuration == null ? 'GA4 pending' : null}
                    definition={DEFS.avgSessionDuration}
                  />
                  <KPICard
                    label="Pages per session"
                    value={data.website.pagesPerSession}
                    change={null}
                    changeLabel={data.website.pagesPerSession == null ? 'GA4 pending' : null}
                    definition={DEFS.pagesPerSession}
                  />
                  <KPICard
                    label="New visitor %"
                    value={data.website.newUserPct != null ? fmt.pct(data.website.newUserPct) : null}
                    change={null}
                    changeLabel={data.website.newUserPct == null ? 'GA4 pending' : null}
                    definition={DEFS.newUserPct}
                  />
                  <KPICard
                    label="Conversion rate"
                    value={data.customers.conversionRate ? fmt.pct(data.customers.conversionRate) : null}
                    change={null}
                    changeLabel="GA4 pending"
                    definition={DEFS.conversion}
                  />
                </div>

                {/* Traffic by channel */}
                <div className="chart-row" style={{ marginTop:10 }}>
                  <ChartCard title="Sessions by channel (week)">
                    {data.website.channels?.length > 0 ? (
                      <ResponsiveContainer width="100%" height={180}>
                        <BarChart data={data.website.channels.slice(0,7)} layout="vertical" margin={{top:0,right:40,bottom:0,left:0}}>
                          <XAxis type="number" tick={{fontSize:9,fill:'#8C8A85'}} axisLine={false} tickLine={false} />
                          <YAxis type="category" dataKey="channel" tick={{fontSize:9,fill:'#5F5E5A'}} axisLine={false} tickLine={false} width={90} />
                          <Tooltip content={({ active, payload, label }) => {
                            if (!active || !payload?.length) return null;
                            const d = data.website.channels.find(c => c.channel === label);
                            return (
                              <div style={{ background:'#FFFFFF', border:'0.5px solid #E0DDD6', borderRadius:6, padding:'7px 10px', fontSize:11 }}>
                                <div style={{ fontWeight:600, color:'#3D3226', marginBottom:3 }}>{label}</div>
                                <div style={{ color:'#5F5E5A' }}>{payload[0].value?.toLocaleString()} sessions ({d?.pct}%)</div>
                                {d?.wow != null && (
                                  <div style={{ color: d.wow >= 0 ? '#5A7A5C' : '#A32D2D', marginTop:2 }}>
                                    {d.wow >= 0 ? '↑' : '↓'} {Math.abs(d.wow)}% WoW
                                  </div>
                                )}
                              </div>
                            );
                          }} />
                          <Bar dataKey="sessions" radius={[0,3,3,0]}>
                            {data.website.channels.slice(0,7).map((entry, i) => {
                              const colors = ['#5A7A5C','#378ADD','#C8763A','#7A5C8A','#3A8A8A','#8A7A3A','#8A3A5C'];
                              return <rect key={i} fill={colors[i % colors.length]} />;
                            })}
                          </Bar>
                        </BarChart>
                      </ResponsiveContainer>
                    ) : (
                      <div style={{display:'flex',alignItems:'center',justifyContent:'center',height:100,color:'#8C8A85',fontSize:12}}>
                        ⏳ Awaiting GA4 connection
                      </div>
                    )}
                  </ChartCard>

                  <ChartCard title="Daily sessions — last 14 days">
                    {data.website.dailySessions?.length > 0 ? (
                      <ResponsiveContainer width="100%" height={180}>
                        <LineChart data={data.website.dailySessions} margin={{top:4,right:8,bottom:0,left:0}}>
                          <XAxis dataKey="date" tick={{fontSize:10,fill:'#8C8A85'}} axisLine={false} tickLine={false} />
                          <YAxis tick={{fontSize:10,fill:'#8C8A85'}} axisLine={false} tickLine={false} width={36} />
                          <Tooltip content={<CustomTooltip />} />
                          <Line type="monotone" dataKey="sessions" stroke="#378ADD" strokeWidth={2} dot={{r:2,fill:'#378ADD'}} activeDot={{r:4}} />
                        </LineChart>
                      </ResponsiveContainer>
                    ) : (
                      <div style={{display:'flex',alignItems:'center',justifyContent:'center',height:100,color:'#8C8A85',fontSize:12}}>
                        ⏳ Awaiting GA4 connection
                      </div>
                    )}
                  </ChartCard>
                </div>

                {/* Channel breakdown table */}
                {data.website.channels?.length > 0 && (
                  <ChartCard title="Channel breakdown" style={{ marginTop:10 }}>
                    <div style={{ display:'grid', gridTemplateColumns:'1fr 80px 60px 70px', gap:'0 8px', fontSize:10 }}>
                      {['Channel','Sessions','Share','WoW'].map(h => (
                        <div key={h} style={{ fontWeight:700, color:'#8C8A85', textTransform:'uppercase', letterSpacing:'0.06em', paddingBottom:6, borderBottom:'1px solid #E0DDD6' }}>{h}</div>
                      ))}
                      {data.website.channels.map((ch, i) => (
                        <React.Fragment key={i}>
                          <div style={{ padding:'5px 0', borderBottom:'0.5px solid #F0EDE6', color:'#3D3226', fontWeight:500 }}>{ch.channel}</div>
                          <div style={{ padding:'5px 0', borderBottom:'0.5px solid #F0EDE6', color:'#1A1A1A', fontFamily:'DM Mono, monospace' }}>{ch.sessions?.toLocaleString()}</div>
                          <div style={{ padding:'5px 0', borderBottom:'0.5px solid #F0EDE6', color:'#5F5E5A' }}>{ch.pct}%</div>
                          <div style={{ padding:'5px 0', borderBottom:'0.5px solid #F0EDE6' }}>
                            {ch.wow != null ? (
                              <span style={{ color: ch.wow >= 0 ? '#5A7A5C' : '#A32D2D', fontWeight:500 }}>
                                {ch.wow >= 0 ? '↑' : '↓'} {Math.abs(ch.wow)}%
                              </span>
                            ) : <span style={{ color:'#C8BFB0' }}>—</span>}
                          </div>
                        </React.Fragment>
                      ))}
                    </div>
                  </ChartCard>
                )}

                {/* Top landing pages */}
                {data.website.topLandingPages?.length > 0 && (
                  <ChartCard title="Top landing pages (week)" style={{ marginTop:10 }}>
                    <div style={{ display:'grid', gridTemplateColumns:'1fr 80px 80px', gap:'0 8px', fontSize:10 }}>
                      {['Page','Sessions','Bounce'].map(h => (
                        <div key={h} style={{ fontWeight:700, color:'#8C8A85', textTransform:'uppercase', letterSpacing:'0.06em', paddingBottom:6, borderBottom:'1px solid #E0DDD6' }}>{h}</div>
                      ))}
                      {data.website.topLandingPages.map((pg, i) => (
                        <React.Fragment key={i}>
                          <div style={{ padding:'5px 0', borderBottom:'0.5px solid #F0EDE6', color:'#3D3226', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', fontFamily:'DM Mono, monospace', fontSize:9 }}>{pg.page}</div>
                          <div style={{ padding:'5px 0', borderBottom:'0.5px solid #F0EDE6', color:'#1A1A1A', fontFamily:'DM Mono, monospace' }}>{pg.sessions?.toLocaleString()}</div>
                          <div style={{ padding:'5px 0', borderBottom:'0.5px solid #F0EDE6', color: pg.bounceRate > 70 ? '#A32D2D' : pg.bounceRate > 50 ? '#854F0B' : '#5A7A5C' }}>{pg.bounceRate}%</div>
                        </React.Fragment>
                      ))}
                    </div>
                  </ChartCard>
                )}

                {/* #4 Growth */}
                <SectionLabel id="sec-growth">Growth & Catalog</SectionLabel>
                <div className="chart-row">
                  <ChartCard title="GMV by brand (week)">
                    <ResponsiveContainer width="100%" height={150}>
                      <BarChart data={(data.orders.gmvByBrand||[]).slice(0,6)} margin={{top:0,right:4,bottom:0,left:0}} layout="vertical">
                        <XAxis type="number" tick={{fontSize:9,fill:'#8C8A85'}} axisLine={false} tickLine={false} tickFormatter={v=>`$${(v/1000).toFixed(0)}k`} />
                        <YAxis type="category" dataKey="brand" tick={{fontSize:9,fill:'#5F5E5A'}} axisLine={false} tickLine={false} width={70} />
                        <Tooltip content={<CustomTooltip prefix="$" />} />
                        <Bar dataKey="gmv" fill="#5A7A5C" radius={[0,3,3,0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </ChartCard>
                  <ChartCard title="GMV by category (week)">
                    <ResponsiveContainer width="100%" height={150}>
                      <BarChart data={(data.orders.gmvByCategory||[]).slice(0,6)} margin={{top:0,right:4,bottom:0,left:0}} layout="vertical">
                        <XAxis type="number" tick={{fontSize:9,fill:'#8C8A85'}} axisLine={false} tickLine={false} tickFormatter={v=>`$${(v/1000).toFixed(0)}k`} />
                        <YAxis type="category" dataKey="category" tick={{fontSize:9,fill:'#5F5E5A'}} axisLine={false} tickLine={false} width={70} />
                        <Tooltip content={<CustomTooltip prefix="$" />} />
                        <Bar dataKey="gmv" fill="#378ADD" radius={[0,3,3,0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  </ChartCard>
                </div>
                {/* #4 Marketplace */}
                <SectionLabel id="sec-marketplace">Marketplace & Supply</SectionLabel>
                <div className="kpi-grid">
                  <KPICard label="Total brands live"       value={fmt.num(data.marketplace.totalBrands)}       change={null} changeLabel={`+${data.marketplace.newBrandsThisWeek} this week`} definition={DEFS.totalBrands} />
                  <KPICard label="Total SKUs live"         value={fmt.num(data.marketplace.totalSKUs)}         change={null} definition={DEFS.totalSKUs} />
                  <KPICard label="New brands (week)"       value={fmt.num(data.marketplace.newBrandsThisWeek)} change={null} definition={DEFS.newBrands} />
                  <KPICard label="Top 5 brand concentration" value={fmt.pct(data.marketplace.brandConcentration)} change={null} definition={DEFS.concentration}
                    drillTitle="Brand GMV breakdown" drillData={(data.marketplace.gmvByBrand||[]).slice(0,8).map(b=>({label:b.brand,value:b.gmv,formatted:fmt.usd(b.gmv)}))} />
                  <KPICard label="Avg fulfillment time"    value={fmt.days(data.marketplace.avgFulfillmentDays)} change={null} definition={DEFS.fulfillment} />
                  <KPICard label="Overall return rate"     value={fmt.pct(data.marketplace.overallReturnRate)}  change={null} definition={DEFS.overallReturn} />
                </div>

                {/* Ask Birch Queries */}
                <SectionLabel id="sec-askbirch">Ask Birch — Customer Queries</SectionLabel>
                <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10 }}>

                  {/* Top queries */}
                  <div style={{ background:'#FFFFFF', border:'0.5px solid #E0DDD6', borderRadius:10, padding:'12px 14px' }}>
                    <div style={{ display:'flex', alignItems:'center', gap:6, marginBottom:10 }}>
                      <span style={{ fontSize:12, fontWeight:600, color:'#3D3226' }}>Top queries (7 days)</span>
                      <span style={{ fontSize:10, background:'#F0EDE6', color:'#5F5E5A', padding:'1px 7px', borderRadius:99, fontWeight:600 }}>
                        {data.askBirch?.total || 0} total
                      </span>
                    </div>
                    {(data.askBirch?.topQueries?.length || 0) === 0 ? (
                      <div style={{ fontSize:12, color:'#8C8A85', padding:'8px 0' }}>No queries yet — data builds as customers chat</div>
                    ) : (
                      <div style={{ display:'grid', gridTemplateColumns:'1fr 36px', gap:'0 8px', fontSize:10 }}>
                        {['Query','#'].map(h => (
                          <div key={h} style={{ fontWeight:700, color:'#8C8A85', textTransform:'uppercase', letterSpacing:'0.06em', paddingBottom:5, borderBottom:'1px solid #E0DDD6' }}>{h}</div>
                        ))}
                        {(data.askBirch.topQueries || []).slice(0, 15).map((q, i) => (
                          <React.Fragment key={i}>
                            <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6', color:'#3D3226', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }} title={q.query}>{q.query}</div>
                            <div style={{ padding:'4px 0', borderBottom:'0.5px solid #F0EDE6', color:'#378ADD', fontWeight:600, fontFamily:'DM Mono, monospace', textAlign:'right' }}>{q.count}</div>
                          </React.Fragment>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Recent chats */}
                  <div style={{ background:'#FFFFFF', border:'0.5px solid #E0DDD6', borderRadius:10, padding:'12px 14px' }}>
                    <div style={{ fontSize:12, fontWeight:600, color:'#3D3226', marginBottom:10 }}>Recent chats</div>
                    {(data.askBirch?.recent?.length || 0) === 0 ? (
                      <div style={{ fontSize:12, color:'#8C8A85', padding:'8px 0' }}>No queries yet</div>
                    ) : (
                      <div style={{ display:'flex', flexDirection:'column', gap:5 }}>
                        {(data.askBirch.recent || []).slice(0, 12).map((q, i) => (
                          <div key={q.sessionId || i} style={{ borderBottom:'0.5px solid #F0EDE6', paddingBottom:5 }}>
                            <div style={{ fontSize:11, color:'#3D3226', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }} title={q.query}>
                              {q.query || '(no title)'}
                            </div>
                            <div style={{ fontSize:10, color:'#8C8A85', marginTop:1, display:'flex', gap:8, alignItems:'center', flexWrap:'wrap' }}>
                              <span>{q.ts ? new Date(q.ts).toLocaleString('en-US', { month:'short', day:'numeric', hour:'2-digit', minute:'2-digit' }) : ''}</span>
                              {q.messageCount != null && <span>{q.messageCount} msg</span>}
                              {q.wasEscalated && <span style={{ color:'#B0483C', fontWeight:600 }}>escalated</span>}
                              {customerAdminUrl(q.customerId) ? (
                                <a href={customerAdminUrl(q.customerId)} target="_blank" rel="noreferrer"
                                   style={{ color:'#378ADD', fontWeight:600, textDecoration:'none' }}>
                                  Customer ↗
                                </a>
                              ) : (
                                <span>guest</span>
                              )}
                              {q.sessionId && (
                                <button onClick={() => setChatSessionId(q.sessionId)}
                                  style={{ border:'none', background:'#F0EDE6', color:'#3D3226', borderRadius:4,
                                           padding:'1px 7px', fontSize:10, fontWeight:600, cursor:'pointer',
                                           fontFamily:'inherit' }}>
                                  View chat
                                </button>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* Browse & download all queries in a date range */}
                  <QueryExport onViewChat={setChatSessionId} />

                </div>

                {/* Email */}
                <SectionLabel id="sec-email">Email & CRM</SectionLabel>
                <div className="kpi-grid">
                  <KPICard label="Total list size" value={fmt.num(data.email.totalListSize)} change={null} definition={DEFS.listSize} />
                  <KPICard label="Open rate"  value={null} change={null} changeLabel="Klaviyo — check dashboard" />
                  <KPICard label="Click rate" value={null} change={null} changeLabel="Klaviyo — check dashboard" />
                </div>

                <div style={{height:40}} />
              </>
            )}
          </div>

          {/* AI chat — desktop inline, mobile floating */}
          <div className="desktop-only" style={{display:'flex',flexDirection:'column',overflow:'hidden'}}>
            <AIChat dashboardData={data} />
          </div>

        </div>
      </div>
      {/* Mobile floating chat */}
      <div style={{}} className="topbar-right-mobile">
        <AIChat dashboardData={data} />
      </div>
      {chatSessionId && (
        <ChatTranscriptModal sessionId={chatSessionId} onClose={() => setChatSessionId(null)} />
      )}
    </>
  );
}
// Mobile topbar fix appended — see inline styles with media query simulation
